/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExamCategory = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const GuidancePost = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'examCategoryId' : IDL.Nat32,
  'body' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const StudyNote = IDL.Record({
  'id' : IDL.Nat32,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'examCategoryId' : IDL.Nat32,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const TutorMentorProfile = IDL.Record({
  'id' : IDL.Nat32,
  'bio' : IDL.Text,
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'hourlyRate' : IDL.Opt(IDL.Nat32),
  'isMentor' : IDL.Bool,
  'exams' : IDL.Vec(IDL.Nat32),
  'availability' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const BookingRequest = IDL.Record({
  'id' : IDL.Nat32,
  'status' : BookingStatus,
  'tutor' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
  'student' : IDL.Principal,
});
export const T = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'expertiseTags' : IDL.Vec(IDL.Text),
});
export const Review = IDL.Record({
  'id' : IDL.Nat32,
  'tutor' : IDL.Principal,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'rating' : IDL.Nat32,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Nat32], [], []),
  'addExamCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat32], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBookingRequest' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat32], []),
  'createGuidancePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat32],
      [IDL.Nat32],
      [],
    ),
  'createReview' : IDL.Func(
      [IDL.Principal, IDL.Nat32, IDL.Text],
      [IDL.Nat32],
      [],
    ),
  'createStudyNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat32],
      [IDL.Nat32],
      [],
    ),
  'createTutorMentorProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Nat32),
        IDL.Text,
        IDL.Opt(IDL.Nat32),
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat32],
      [],
    ),
  'createUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteGuidancePost' : IDL.Func([IDL.Nat32], [], []),
  'deleteStudyNote' : IDL.Func([IDL.Nat32], [], []),
  'getAllExamCategories' : IDL.Func([], [IDL.Vec(ExamCategory)], ['query']),
  'getAllGuidancePosts' : IDL.Func([], [IDL.Vec(GuidancePost)], ['query']),
  'getAllStudyNotes' : IDL.Func([], [IDL.Vec(StudyNote)], ['query']),
  'getAllTutorMentorProfiles' : IDL.Func(
      [],
      [IDL.Vec(TutorMentorProfile)],
      ['query'],
    ),
  'getBookingRequestsForTutor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(BookingRequest)],
      ['query'],
    ),
  'getBookmarks' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat32)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReviewsForTutor' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Review)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([T], [], []),
  'searchNotesByTitle' : IDL.Func([IDL.Text], [IDL.Vec(StudyNote)], ['query']),
  'updateBookingRequestStatus' : IDL.Func([IDL.Nat32, BookingStatus], [], []),
  'updateGuidancePost' : IDL.Func([IDL.Nat32, IDL.Text, IDL.Text], [], []),
  'updateStudyNote' : IDL.Func(
      [IDL.Nat32, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExamCategory = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Time = IDL.Int;
  const GuidancePost = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'examCategoryId' : IDL.Nat32,
    'body' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const StudyNote = IDL.Record({
    'id' : IDL.Nat32,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'examCategoryId' : IDL.Nat32,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const TutorMentorProfile = IDL.Record({
    'id' : IDL.Nat32,
    'bio' : IDL.Text,
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'hourlyRate' : IDL.Opt(IDL.Nat32),
    'isMentor' : IDL.Bool,
    'exams' : IDL.Vec(IDL.Nat32),
    'availability' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const BookingRequest = IDL.Record({
    'id' : IDL.Nat32,
    'status' : BookingStatus,
    'tutor' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
    'student' : IDL.Principal,
  });
  const T = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'expertiseTags' : IDL.Vec(IDL.Text),
  });
  const Review = IDL.Record({
    'id' : IDL.Nat32,
    'tutor' : IDL.Principal,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'rating' : IDL.Nat32,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Nat32], [], []),
    'addExamCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat32], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBookingRequest' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Nat32],
        [],
      ),
    'createGuidancePost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat32],
        [IDL.Nat32],
        [],
      ),
    'createReview' : IDL.Func(
        [IDL.Principal, IDL.Nat32, IDL.Text],
        [IDL.Nat32],
        [],
      ),
    'createStudyNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat32],
        [IDL.Nat32],
        [],
      ),
    'createTutorMentorProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Nat32),
          IDL.Text,
          IDL.Opt(IDL.Nat32),
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat32],
        [],
      ),
    'createUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteGuidancePost' : IDL.Func([IDL.Nat32], [], []),
    'deleteStudyNote' : IDL.Func([IDL.Nat32], [], []),
    'getAllExamCategories' : IDL.Func([], [IDL.Vec(ExamCategory)], ['query']),
    'getAllGuidancePosts' : IDL.Func([], [IDL.Vec(GuidancePost)], ['query']),
    'getAllStudyNotes' : IDL.Func([], [IDL.Vec(StudyNote)], ['query']),
    'getAllTutorMentorProfiles' : IDL.Func(
        [],
        [IDL.Vec(TutorMentorProfile)],
        ['query'],
      ),
    'getBookingRequestsForTutor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(BookingRequest)],
        ['query'],
      ),
    'getBookmarks' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat32)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReviewsForTutor' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Review)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(T)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([T], [], []),
    'searchNotesByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudyNote)],
        ['query'],
      ),
    'updateBookingRequestStatus' : IDL.Func([IDL.Nat32, BookingStatus], [], []),
    'updateGuidancePost' : IDL.Func([IDL.Nat32, IDL.Text, IDL.Text], [], []),
    'updateStudyNote' : IDL.Func(
        [IDL.Nat32, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };