/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : number,
  'status' : BookingStatus,
  'tutor' : Principal,
  'message' : string,
  'timestamp' : Time,
  'student' : Principal,
}
export type BookingStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface ExamCategory {
  'id' : number,
  'name' : string,
  'description' : string,
}
export interface GuidancePost {
  'id' : number,
  'title' : string,
  'examCategoryId' : number,
  'body' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface Review {
  'id' : number,
  'tutor' : Principal,
  'text' : string,
  'author' : Principal,
  'timestamp' : Time,
  'rating' : number,
}
export interface StudyNote {
  'id' : number,
  'title' : string,
  'content' : string,
  'subject' : string,
  'examCategoryId' : number,
  'author' : Principal,
  'timestamp' : Time,
}
export interface T {
  'bio' : string,
  'displayName' : string,
  'expertiseTags' : Array<string>,
}
export type Time = bigint;
export interface TutorMentorProfile {
  'id' : number,
  'bio' : string,
  'subjects' : Array<string>,
  'name' : string,
  'user' : Principal,
  'hourlyRate' : [] | [number],
  'isMentor' : boolean,
  'exams' : Uint32Array,
  'availability' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[number], undefined>,
  'addExamCategory' : ActorMethod<[string, string], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBookingRequest' : ActorMethod<[Principal, string], number>,
  'createGuidancePost' : ActorMethod<[string, string, number], number>,
  'createReview' : ActorMethod<[Principal, number, string], number>,
  'createStudyNote' : ActorMethod<[string, string, string, number], number>,
  'createTutorMentorProfile' : ActorMethod<
    [
      string,
      Array<string>,
      Uint32Array,
      string,
      [] | [number],
      string,
      boolean,
    ],
    number
  >,
  'createUserProfile' : ActorMethod<[string, string, Array<string>], undefined>,
  'deleteGuidancePost' : ActorMethod<[number], undefined>,
  'deleteStudyNote' : ActorMethod<[number], undefined>,
  'getAllExamCategories' : ActorMethod<[], Array<ExamCategory>>,
  'getAllGuidancePosts' : ActorMethod<[], Array<GuidancePost>>,
  'getAllStudyNotes' : ActorMethod<[], Array<StudyNote>>,
  'getAllTutorMentorProfiles' : ActorMethod<[], Array<TutorMentorProfile>>,
  'getBookingRequestsForTutor' : ActorMethod<
    [Principal],
    Array<BookingRequest>
  >,
  'getBookmarks' : ActorMethod<[Principal], Uint32Array>,
  'getCallerUserProfile' : ActorMethod<[], [] | [T]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReviewsForTutor' : ActorMethod<[Principal], Array<Review>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [T]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[T], undefined>,
  'searchNotesByTitle' : ActorMethod<[string], Array<StudyNote>>,
  'updateBookingRequestStatus' : ActorMethod<
    [number, BookingStatus],
    undefined
  >,
  'updateGuidancePost' : ActorMethod<[number, string, string], undefined>,
  'updateStudyNote' : ActorMethod<[number, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];