/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookingRequest {
  'id' : number,
  'status' : BookingStatus,
  'tutor' : Principal,
  'message' : string,
  'timestamp' : Time,
  'student' : Principal,
}
export type BookingStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface ExamCategory {
  'id' : number,
  'name' : string,
  'description' : string,
}
export interface GuidancePost {
  'id' : number,
  'title' : string,
  'examCategoryId' : number,
  'body' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface Review {
  'id' : number,
  'tutor' : Principal,
  'text' : string,
  'author' : Principal,
  'timestamp' : Time,
  'rating' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface StudyNote {
  'id' : number,
  'title' : string,
  'content' : string,
  'subject' : string,
  'examCategoryId' : number,
  'fileName' : [] | [string],
  'fileType' : [] | [string],
  'author' : Principal,
  'fileId' : [] | [string],
  'timestamp' : Time,
}
export interface T {
  'bio' : string,
  'displayName' : string,
  'expertiseTags' : Array<string>,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TutorMentorProfile {
  'id' : number,
  'bio' : string,
  'subjects' : Array<string>,
  'name' : string,
  'user' : Principal,
  'hourlyRate' : [] | [number],
  'isMentor' : boolean,
  'exams' : Uint32Array,
  'availability' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[number], undefined>,
  'addExamCategory' : ActorMethod<[string, string], number>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimInitialAdmin' : ActorMethod<[], string>,
  'createBookingRequest' : ActorMethod<[Principal, string], number>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGuidancePost' : ActorMethod<[string, string, number], number>,
  'createReview' : ActorMethod<[Principal, number, string], number>,
  'createStudyNote' : ActorMethod<
    [
      string,
      string,
      string,
      number,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    number
  >,
  'createTutorMentorProfile' : ActorMethod<
    [
      string,
      Array<string>,
      Uint32Array,
      string,
      [] | [number],
      string,
      boolean,
    ],
    number
  >,
  'deleteGuidancePost' : ActorMethod<[number], undefined>,
  'deleteStudyNote' : ActorMethod<[number], undefined>,
  'getAdminStatus' : ActorMethod<[], boolean>,
  'getAllExamCategories' : ActorMethod<[], Array<ExamCategory>>,
  'getAllGuidancePosts' : ActorMethod<[], Array<GuidancePost>>,
  'getAllStudyNotes' : ActorMethod<[], Array<StudyNote>>,
  'getAllTutorMentorProfiles' : ActorMethod<[], Array<TutorMentorProfile>>,
  'getBookingRequestsForTutor' : ActorMethod<
    [Principal],
    Array<BookingRequest>
  >,
  'getBookmarks' : ActorMethod<[Principal], Uint32Array>,
  'getCallerUserProfile' : ActorMethod<[], [] | [T]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getReviewsForTutor' : ActorMethod<[Principal], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [T]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[T], undefined>,
  'searchNotesByTitle' : ActorMethod<[string], Array<StudyNote>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  /**
   * / TRANSFORM CALLBACK REQUIRED FOR HTTP OUTCALLS (e.g. Stripe)
   */
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingRequestStatus' : ActorMethod<
    [number, BookingStatus],
    undefined
  >,
  'updateGuidancePost' : ActorMethod<[number, string, string], undefined>,
  'updateStudyNote' : ActorMethod<
    [
      number,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];