/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TutorMentorProfile {
    id: number;
    bio: string;
    subjects: Array<string>;
    name: string;
    user: Principal;
    hourlyRate?: number;
    isMentor: boolean;
    exams: Uint32Array;
    availability: string;
}
export interface ExamCategory {
    id: number;
    name: string;
    description: string;
}
export type Time = bigint;
export interface T {
    bio: string;
    displayName: string;
    expertiseTags: Array<string>;
}
export interface BookingRequest {
    id: number;
    status: BookingStatus;
    tutor: Principal;
    message: string;
    timestamp: Time;
    student: Principal;
}
export interface StudyNote {
    id: number;
    title: string;
    content: string;
    subject: string;
    examCategoryId: number;
    author: Principal;
    timestamp: Time;
}
export interface Review {
    id: number;
    tutor: Principal;
    text: string;
    author: Principal;
    timestamp: Time;
    rating: number;
}
export interface GuidancePost {
    id: number;
    title: string;
    examCategoryId: number;
    body: string;
    author: Principal;
    timestamp: Time;
}
export enum BookingStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBookmark(itemId: number): Promise<void>;
    addExamCategory(name: string, description: string): Promise<number>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBookingRequest(tutor: Principal, message: string): Promise<number>;
    createGuidancePost(title: string, body: string, examCategoryId: number): Promise<number>;
    createReview(tutor: Principal, rating: number, text: string): Promise<number>;
    createStudyNote(title: string, content: string, subject: string, examCategoryId: number): Promise<number>;
    createTutorMentorProfile(name: string, subjects: Array<string>, exams: Uint32Array, availability: string, hourlyRate: number | null, bio: string, isMentor: boolean): Promise<number>;
    createUserProfile(displayName: string, bio: string, expertiseTags: Array<string>): Promise<void>;
    deleteGuidancePost(id: number): Promise<void>;
    deleteStudyNote(id: number): Promise<void>;
    getAllExamCategories(): Promise<Array<ExamCategory>>;
    getAllGuidancePosts(): Promise<Array<GuidancePost>>;
    getAllStudyNotes(): Promise<Array<StudyNote>>;
    getAllTutorMentorProfiles(): Promise<Array<TutorMentorProfile>>;
    getBookingRequestsForTutor(tutor: Principal): Promise<Array<BookingRequest>>;
    getBookmarks(user: Principal): Promise<Uint32Array>;
    getCallerUserProfile(): Promise<T | null>;
    getCallerUserRole(): Promise<UserRole>;
    getReviewsForTutor(tutor: Principal): Promise<Array<Review>>;
    getUserProfile(user: Principal): Promise<T | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: T): Promise<void>;
    searchNotesByTitle(queryText: string): Promise<Array<StudyNote>>;
    updateBookingRequestStatus(id: number, status: BookingStatus): Promise<void>;
    updateGuidancePost(id: number, title: string, body: string): Promise<void>;
    updateStudyNote(id: number, title: string, content: string, subject: string): Promise<void>;
}
import type { BookingRequest as _BookingRequest, BookingStatus as _BookingStatus, T as _T, Time as _Time, TutorMentorProfile as _TutorMentorProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBookmark(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookmark(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookmark(arg0);
            return result;
        }
    }
    async addExamCategory(arg0: string, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.addExamCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExamCategory(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBookingRequest(arg0: Principal, arg1: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createBookingRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBookingRequest(arg0, arg1);
            return result;
        }
    }
    async createGuidancePost(arg0: string, arg1: string, arg2: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuidancePost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuidancePost(arg0, arg1, arg2);
            return result;
        }
    }
    async createReview(arg0: Principal, arg1: number, arg2: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0, arg1, arg2);
            return result;
        }
    }
    async createStudyNote(arg0: string, arg1: string, arg2: string, arg3: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudyNote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudyNote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTutorMentorProfile(arg0: string, arg1: Array<string>, arg2: Uint32Array, arg3: string, arg4: number | null, arg5: string, arg6: boolean): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.createTutorMentorProfile(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTutorMentorProfile(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async createUserProfile(arg0: string, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteGuidancePost(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGuidancePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGuidancePost(arg0);
            return result;
        }
    }
    async deleteStudyNote(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudyNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudyNote(arg0);
            return result;
        }
    }
    async getAllExamCategories(): Promise<Array<ExamCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExamCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExamCategories();
            return result;
        }
    }
    async getAllGuidancePosts(): Promise<Array<GuidancePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGuidancePosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGuidancePosts();
            return result;
        }
    }
    async getAllStudyNotes(): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudyNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudyNotes();
            return result;
        }
    }
    async getAllTutorMentorProfiles(): Promise<Array<TutorMentorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTutorMentorProfiles();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTutorMentorProfiles();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingRequestsForTutor(arg0: Principal): Promise<Array<BookingRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingRequestsForTutor(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingRequestsForTutor(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookmarks(arg0: Principal): Promise<Uint32Array> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookmarks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookmarks(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<T | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsForTutor(arg0: Principal): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsForTutor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsForTutor(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<T | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchNotesByTitle(arg0: string): Promise<Array<StudyNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchNotesByTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchNotesByTitle(arg0);
            return result;
        }
    }
    async updateBookingRequestStatus(arg0: number, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingRequestStatus(arg0, to_candid_BookingStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingRequestStatus(arg0, to_candid_BookingStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateGuidancePost(arg0: number, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuidancePost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuidancePost(arg0, arg1, arg2);
            return result;
        }
    }
    async updateStudyNote(arg0: number, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudyNote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudyNote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_BookingRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingRequest): BookingRequest {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TutorMentorProfile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TutorMentorProfile): TutorMentorProfile {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T]): T | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    status: _BookingStatus;
    tutor: Principal;
    message: string;
    timestamp: _Time;
    student: Principal;
}): {
    id: number;
    status: BookingStatus;
    tutor: Principal;
    message: string;
    timestamp: Time;
    student: Principal;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n11(_uploadFile, _downloadFile, value.status),
        tutor: value.tutor,
        message: value.message,
        timestamp: value.timestamp,
        student: value.student
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: number;
    bio: string;
    subjects: Array<string>;
    name: string;
    user: Principal;
    hourlyRate: [] | [number];
    isMentor: boolean;
    exams: Uint32Array;
    availability: string;
}): {
    id: number;
    bio: string;
    subjects: Array<string>;
    name: string;
    user: Principal;
    hourlyRate?: number;
    isMentor: boolean;
    exams: Uint32Array;
    availability: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        subjects: value.subjects,
        name: value.name,
        user: value.user,
        hourlyRate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.hourlyRate)),
        isMentor: value.isMentor,
        exams: value.exams,
        availability: value.availability
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "rejected" in value ? BookingStatus.rejected : "accepted" in value ? BookingStatus.accepted : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TutorMentorProfile>): Array<TutorMentorProfile> {
    return value.map((x)=>from_candid_TutorMentorProfile_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingRequest>): Array<BookingRequest> {
    return value.map((x)=>from_candid_BookingRequest_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.rejected ? {
        rejected: null
    } : value == BookingStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
